spring:
  application:
    name: achievement-service
  
  datasource:
    url: jdbc:sqlite:../data/achievement.db
    username: 
    password: 
    driver-class-name: org.sqlite.JDBC
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.sqlite.hibernate.dialect.SQLiteDialect
  
  flyway:
    enabled: false

server:
  port: 8080

logging:
  level:
    com.example.achievement: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG

dingtalk:
  corpId: ding4651594f561e9defacaaa37764f94726
  appKey: dingrx0rajaydrsvj9kp
  appSecret: xJ37zMtw9hm51C5RpznJOQImb8T-LemJZNch3pTTPxUu9UTbNMc9l_WzYFBcwL5n
  baseId: 7dx2rn0JbY4y54XwI2gz73NMVMGjLRb3
  operatorId: hrLezKRiP5iSDyzxF9xpIYPwiEiE
  data-warehouse-base-id: y20BglGWO2y56y7nC0aDvlb08A7depqY

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
